### ISSUE TITLE
Bitte die github actions wieder aktivieren

### ISSUE THREAD

**Issue by derreisende77** [fnogatz/RKI-Data-Diff#3]
Aufgrund Inaktivität wurde die action für den täglichen dump deaktiviert und muss wieder aktiviert werden.

**Comment by fnogatz** [comment]
Danke fürs Bescheidgeben! Ich habe die Daten vom 2022-01-09 bis 2022-02-16 lokal neu eingespielt und den aktuellsten Datenstand ins Repository geladen, siehe [`dump`-Branch](https://github.com/fnogatz/RKI-Data-Diff/tree/dump).
