### ISSUE TITLE
new datasourceby RKI

### ISSUE THREAD

**Issue by Rubber1Duck** [fnogatz/RKI-Data-Diff#4]
hopefully you saw this .....
[https://arcgis.esri.de/aenderung-des-rki-covid-19-datensatzes/](https://arcgis.esri.de/aenderung-des-rki-covid-19-datensatzes/)

**Comment by fnogatz** [comment]
Hi! Thank you for the note on the updated dataset. In our [`replay.sh`](https://github.com/fnogatz/RKI-Data-Diff/blob/main/replay.sh), we use the endpoint `https://www.arcgis.com/sharing/rest/content/items/f10774f1c63e40168479a1feb6c7ca74/data`, which does not seem to be affected by the recent changes of ArcGIS/ESRI. Have you experienced any problems with our scripts or data, respectively?

**Comment by Rubber1Duck** [comment]
> Have you experienced any problems with our scripts or data, respectively?

No, i don`t. See this only as a hint ..................
