### ISSUE TITLE
GH update action fehlgeschlagen

### ISSUE THREAD

**Issue by derreisende77** [fnogatz/RKI-Data-Diff#6]
Der heutige Dump hat leider wieder nicht funktioniert.

**Comment by derreisende77** [comment]
Die actions sind dauerhaft defekt zur Zeit.
Besteht ggf. die Möglichkeit, die Dateien via FTP zur Verfügung zu stellen?

**Comment by fnogatz** [comment]
Das liegt daran, dass das RKI in den vergangenen Tagen die CSV-Datei nicht mehr zur gleichen Zeit in aller Früh zur Verfügung stellen konnte wie zuvor. Unser tägliches Update-Script bricht daher ab. Ich habe in 369c73722cc64b69556370805812774bd4e6ee66 den Lauf der GitHub Action nun um eine Stunde nach hinten verlegt. Mal sehen, ob das schon reicht.

Für die Tage 2022-03-04 bis 2022-03-07 habe ich die fehlenden Daten auch ergänzt.

**Comment by fnogatz** [comment]
Heute lief die GitHub Action wieder durch und hat Commit cdbe55170653a28166b23973837e327048bcfb42 erstellt. Ich werde das aber weiter beobachten.
